# Generated by Django 6.0.5 on 2026-06-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/'),
        ),
    ]
