# Generated by Django 6.0.5 on 2026-07-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_alter_post_options_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
